{% set version = "2.0.16" %}


package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: 393de05007c314ac7c6c85156cec1b6dbbb0a93a8b620797aeb28bd7178a4ab2

build:
  noarch: python
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - findid = libcomcat.bin.findid:main
    - getcsv = libcomcat.bin.getcsv:main
    - geteventhist = libcomcat.bin.geteventhist:main
    - getmags = libcomcat.bin.getmags:main
    - getpager = libcomcat.bin.getpager:main
    - getphases = libcomcat.bin.getphases:main
    - getproduct = libcomcat.bin.getproduct:main
  
requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - numpy <=1.21
    - pandas
    - xlrd
    - xlwt
    - openpyxl
    - xlsxwriter
    - impactutils
    - obspy
    - pyproj

test:
  commands:
    - findid --help
    - getcsv --help
    - geteventhist --help
    - getmags --help
    - getpager --help
    - getphases --help
    - getproduct --help
    
  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
