{% set version = "1.3.2" %}


package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: 9590724d69e6cec43b8f2fe1b967e48d5ff0e7f19540231edd49086ccd6d7b16

build:
  noarch: python
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  
requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - numpy >=1.14
    - pandas
    - xlrd
    - xlwt
    - openpyxl
    - xlsxwriter
    - impactutils
    - obspy

test:
  commands:
    - findid --help
    - getcsv --help
    - geteventhist --help
    - getimpact --help
    - getmags --help
    - getpager --help
    - getphases --help
    - getproduct --help
    
  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
