{% set version = "1.2.10" %}

package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: 57442327ac694ff7f0c4f9b0aa8e6210a2a1718116f0dbdea89f573d9ef4be55x

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  
requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python
    - python-dateutil
    - numpy >=1.14
    - pandas
    - xlrd
    - xlwt
    - openpyxl
    - xlsxwriter
    - impactutils
    - obspy

test:

  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
