{% set name = "usgs-libcomcat" %}
{% set version = "2.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/usgs-libcomcat-{{ version }}.tar.gz
  sha256: 3cd9a0922ad7a6e5a47ce418a734b79171f50d222025cc0f7b3026315122b3b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - esi-utils-geo
    - esi-utils-time
    - esi-utils-io
    - fiona >=1.8.20
    - h5py
    - numpy >=1.21
    - obspy >=1.2.1
    - pandas >=1.3.3
    - openpyxl >=3.0.6
    - geopy >=2.1.0
    - xlsxwriter >=3.0.1

test:
  imports:
    - usgs_libcomcat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/usgs-libcomcat/
  summary: Python wrapper around ComCat web API
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
