{% set version = "2.0.1" %}


package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: c0267561038df473495ae7685c0aa92275383a522ff6f1f19a140a23ebfca2a0

build:
  noarch: python
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - findid = libcomcat.bin.findid:main
    - getcsv = libcomcat.bin.getcsv:main
    - geteventhist = libcomcat.bin.geteventhist:main
    - getmags = libcomcat.bin.getmags:main
    - getpager = libcomcat.bin.getpager:main
    - getphases = libcomcat.bin.getphases:main
    - getproduct = libcomcat.bin.getproduct:main
  
requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - numpy >=1.14
    - pandas
    - xlrd
    - xlwt
    - openpyxl
    - xlsxwriter
    - impactutils
    - obspy

test:
  commands:
    - findid --help
    - getcsv --help
    - geteventhist --help
    - getmags --help
    - getpager --help
    - getphases --help
    - getproduct --help
    
  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
