{% set version = "1.2.12" %}

package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: c74d279b5c5974e77cc57430f78bd95b14f0405e68f29a03c18498a66c717c0f

build:
  noarch: python
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python >=3
    - pip
  run:
    - python
    - python-dateutil
    - numpy >=1.14
    - pandas
    - xlrd
    - xlwt
    - openpyxl
    - xlsxwriter
    - impactutils
    - obspy

test:

  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
