{% set version = "1.2.22" %}


package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: ba5804a3e590b92677fb80fef21124368674a006c4acf137337137a42501fbd8

build:
  noarch: python
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil
    - numpy >=1.14
    - pandas
    - xlrd
    - xlwt
    - openpyxl
    - xlsxwriter
    - impactutils
    - obspy

test:

  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
