{% set version = "1.2.10" %}

package:
  name: libcomcat
  version: {{ version }}

source:
  url: https://github.com/usgs/libcomcat/archive/{{ version }}.tar.gz
  sha256: 57442327ac694ff7f0c4f9b0aa8e6210a2a1718116f0dbdea89f573d9ef4be55

build:
  number: 0
  skip: True  # [py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.4.1
    - numpy >=1.0
    - pandas >=0.8.1
    - xlrd >=0.9.4
    - xlwt >=1.0.0
    - openpyxl >=1.8.5
    - xlsxwriter >=0.7.3
    - impactutils >=0.7
    - obspy >=1.0.2

test:

  imports:
    - libcomcat

about:
  home: https://github.com/usgs/libcomcat
  license: Public Domain
  summary: 'Python wrapper around ANSS ComCat API (plus tools).'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
