{% set name = "usgs-libcomcat" %}
{% set version = "2.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 78a6589b6cf7d7bd8f90aab96691f91b96c0c9351b11b503921316defd6222e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - esi-utils-geo
    - esi-utils-time
    - esi-utils-io
    - fiona >=1.8.20
    - h5py
    - numpy >=1.21
    - obspy >=1.2.1
    - pandas >=1.3.3
    - openpyxl >=3.0.6
    - geopy >=2.1.0
    - xlsxwriter >=3.0.1

test:
  imports:
    - libcomcat
  # cannot run pip check b/c esi-utils-time depends on beautifulsoup4,
  # and pip doesn't know that bs4 is beautifulsoup4.
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://pypi.org/project/usgs-libcomcat/
  summary: Python wrapper around ComCat web API
  license: Unlicense
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
