# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BFKzrH5gEhlat9NZJfVMamBBdSdFV3+9qisNQmE07FIlrHTu3n7Y9Dueswjusd0ywfDplUFC6HUTOAb6g4rvYQhhHP2VLuQKkSYA0VTKXooIgsQejN10hBcMydCZtrXjJ/t++/zaeHzfSLn0YBpZZiwwGK52ojkfpXGxQJ7N7AtLrQqwI04LaFPjKvCSZFW21NJ7wsKVSCVXJEjpmPm6IXiPDiW5L4DUDSEsK2/gCIqcdz46QWsWncfJ7dBHkukdgdji39m9ZIF5qpJY7ojRXmZxOFJBXLFc7Zv2ysrgzbRDIuqGvi7DcUlvsFhMZJdT2+CQ6g+cbEvn0Nw82bto0YZ3LiPoF33paoSyt4QkLJlA5/w6BnO6neG8fxSHYhOylWtN1ykbyAmx6rMTRSAhWew21gbrMw0ewoQSeMlK/kz7Ef/Emt49vCglBRqpaxv8m4GmD/3/bnRgm8JyhLsY87eEf9OlrN7kqk/ewDjmmg+WKHqM9u3Z3frDHps9H9b1sPx3eiXTFfQxyn3f8uxG1A5VMoRCy/SNLIjYPIy83zM30QdeIK6aA+xwbRLl/cHTDHFr5RBVqn84IdkLeBKBxBlekDARk9aGh7wssLLaQGGTU024x4c95e/0WG1QUgste7OEpVp6c6ZFO9CdhoY7bBfD3E6C6YEULDB0lwChQV0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
