travis:
  secure:
    BINSTAR_TOKEN: E6445aQe4Zzx3ujtKIkkTDJiIERY2E+3ka60YZj/Z83Av5QKg+IDYWMkId1ihInWnzVtfZVX6FHV6LIZQI9PFALSKglDosO6FoNi5jTwYn47Q8nzWqAb2j38Y7JAtvTdcScgmoHWKX+dtIXZrd8HfXYc6ST5v73bzWMFFJqjBucoXEFb9mezxeYowABC8H9UaTURvYSlAen8NqbpUb4QPZeZhdZJMzjGzPeO0cQuyH+R5mLnpV/c1yYMxOnKSRNrdmAJcEZKIYDlSaW9Fpz3yYIwe4cjZo8i0WJ4AvQo6WnhJDRoSyRQ5X3bKbrQGcaPET6uj/P2C1qRRLAs/rbnG7Nneaw8xWC7h0+XV32dN08TtNz0G45Qzt39sN9MEQO9YvsfZ4WOZeCbXs7ozEF69HcxW+K6/S2I8xdBLuESScQ3m0ONOen8Jwk1fS1NpgnBA7wq2Zvan+c15vU10GP5H1Y93INZcHh96gZH6QqZicOX9njgjRIazd2N4M/JTFsaM4XQmgCeiy9DK2is0UKqjC4sZOvsp6Fmw05G1R4Ku21CyC4Dtq4633/00Ypwvm7Sen/AKVu9TDxoxyLYZLn0bebjfqiMyifpsyDVknalKJkWhW7nQnK+Z/N5uI9xHte8vLXlVo7zc2S01qTzwSjS5Lt7AHdYe0LOnzfSE1IaurY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
