travis:
  secure:
    BINSTAR_TOKEN: BFKzrH5gEhlat9NZJfVMamBBdSdFV3+9qisNQmE07FIlrHTu3n7Y9Dueswjusd0ywfDplUFC6HUTOAb6g4rvYQhhHP2VLuQKkSYA0VTKXooIgsQejN10hBcMydCZtrXjJ/t++/zaeHzfSLn0YBpZZiwwGK52ojkfpXGxQJ7N7AtLrQqwI04LaFPjKvCSZFW21NJ7wsKVSCVXJEjpmPm6IXiPDiW5L4DUDSEsK2/gCIqcdz46QWsWncfJ7dBHkukdgdji39m9ZIF5qpJY7ojRXmZxOFJBXLFc7Zv2ysrgzbRDIuqGvi7DcUlvsFhMZJdT2+CQ6g+cbEvn0Nw82bto0YZ3LiPoF33paoSyt4QkLJlA5/w6BnO6neG8fxSHYhOylWtN1ykbyAmx6rMTRSAhWew21gbrMw0ewoQSeMlK/kz7Ef/Emt49vCglBRqpaxv8m4GmD/3/bnRgm8JyhLsY87eEf9OlrN7kqk/ewDjmmg+WKHqM9u3Z3frDHps9H9b1sPx3eiXTFfQxyn3f8uxG1A5VMoRCy/SNLIjYPIy83zM30QdeIK6aA+xwbRLl/cHTDHFr5RBVqn84IdkLeBKBxBlekDARk9aGh7wssLLaQGGTU024x4c95e/0WG1QUgste7OEpVp6c6ZFO9CdhoY7bBfD3E6C6YEULDB0lwChQV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
